name: word
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  sqflite: ^2.0.2+1
  path_provider: ^2.0.11
  io: ^1.0.3
  flutter_screenutil: ^5.5.3+2
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3 # これを追加する
  json_serializable: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11 # これを追加する
  freezed: ^2.0.3+1 # これを追加する

flutter:

  uses-material-design: true
